vich_uploader:
    db_driver: orm

    mappings:
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/image/users'


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true